### ISSUE TITLE
GHA version

### ISSUE THREAD

**Issue by xarthurx** [arendvw/clipper#1]
Hi, great plugin for grasshopper.

However, is it possible to implement it into a .gha file, similar with other grasshopper plugins?
It will make life a lot easier when reinstall system or move around systems to just copy all the gha file in a flash drive.

Sincerely,

**Comment by arendvw** [comment]
Hi maniux, the rhi file is actually just a zip file that contains 3 files:
the .rhp file for the rhino plugin (you can use the offset commands also from rhino, if you install this). The .gha file, and the .dll file with the common tools. If you just require the grasshopper file you can just copy the .dll and the .gha file to where ever you wish.

I'm currently not able to upload a new version, but it's also possible to add them as seperate files.

**Comment by xarthurx** [comment]
OK, thank you for the info.
