### ISSUE TITLE
N Line & N Values.. Single Output..

### ISSUE THREAD

**Issue by khatriharsh** [arendvw/clipper#5]
![273393593-0ca8fef7-561c-422d-be0e-9a8f9f724041.png](https://github.com/arendvw/clipper/assets/50658843/de2bffc8-b57a-4d36-b60b-49a43fc8374f)

Need a solution to this.. Please help me.. Not a coder.. just a enthusiast.. trying to find it's solution for last 2 months..

**Comment by arendvw** [comment]
Hi khatirharsh, this is a support question for grasshopper. Please reach out to the [discourse forum of mcneel](https://discourse.mcneel.com) for this, so that your help is also usable by others. There are more smart minds that can help you solve this.
