### ISSUE TITLE
PolyOffset with different distances

### ISSUE THREAD

**Issue by FranciscoCTI** [arendvw/clipper#6]
Hello, i´m a AEC developer using Clipper for Grasshopper.
I need to do an offset of a polygon but with different distances for each side, is it possible?
Thanks for the great tool.

**Comment by arendvw** [comment]
Ahh, unfortunately - the underlying clipper offset does not offer this. There are some [theoretical algorithms](https://www.sthu.org/research/straightskeleton/) that could do that in theory, but I've not seen any implementations in C# yet.

**Comment by FranciscoCTI** [comment]
Thanks for the answer. At least i know now i have to try another options.
